name: Standard On-Push Build

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/$(echo $GITHUB_REPOSITORY | tr A-Z a-z):$(echo $GITHUB_SHA | cut -c1-8)
